/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab11;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeremy
 */
public class RockPaperScissorsLizardSpock extends javax.swing.JFrame {

    /**
     * Creates new form RockPaperScissorsLizardSpock
     */
    public RockPaperScissorsLizardSpock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice = new javax.swing.ButtonGroup();
        playerChoice = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        rock = new javax.swing.JRadioButton();
        paper = new javax.swing.JRadioButton();
        scissors = new javax.swing.JRadioButton();
        lizard = new javax.swing.JRadioButton();
        spock = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        play = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pScore = new javax.swing.JTextField();
        cScore = new javax.swing.JTextField();
        quit = new javax.swing.JButton();

        playerChoice.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rock v Paper v Scissors v Lizard v Spock");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label.setText("Your Choice");

        choice.add(rock);
        rock.setText("Rock");
        rock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockActionPerformed(evt);
            }
        });

        choice.add(paper);
        paper.setText("Paper");
        paper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperActionPerformed(evt);
            }
        });

        choice.add(scissors);
        scissors.setText("Scissors");
        scissors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scissorsActionPerformed(evt);
            }
        });

        choice.add(lizard);
        lizard.setText("Lizard");
        lizard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lizardActionPerformed(evt);
            }
        });

        choice.add(spock);
        spock.setText("Spock");
        spock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spockActionPerformed(evt);
            }
        });

        message.setColumns(20);
        message.setRows(5);
        jScrollPane1.setViewportView(message);

        play.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        play.setText("RockPaperScissorsLizardSpock!");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        jLabel1.setText("Player's Score");

        jLabel2.setText("Computer's Score");

        pScore.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pScore.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pScore.setText("0");
        pScore.setEnabled(false);

        cScore.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cScore.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cScore.setText("0");
        cScore.setEnabled(false);

        quit.setText("QUIT");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(spock)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quit))
                        .addComponent(play, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lizard)
                                .addComponent(scissors)
                                .addComponent(paper)
                                .addComponent(rock))
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(25, 25, 25)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pScore)
                                .addComponent(cScore)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(paper)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(scissors)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lizard)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spock))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(quit)))
                        .addGap(18, 18, 18)
                        .addComponent(play, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(pScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    private void rockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rockActionPerformed
        playerChoice.setText("1");
    }//GEN-LAST:event_rockActionPerformed

    private void paperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperActionPerformed
        playerChoice.setText("2");
    }//GEN-LAST:event_paperActionPerformed

    private void scissorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scissorsActionPerformed
        playerChoice.setText("3");
    }//GEN-LAST:event_scissorsActionPerformed

    private void lizardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lizardActionPerformed
        playerChoice.setText("4");
    }//GEN-LAST:event_lizardActionPerformed

    private void spockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spockActionPerformed
        playerChoice.setText("5");
    }//GEN-LAST:event_spockActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        Random ranD = new Random();
        int comChoice = ranD.nextInt(6);
        int userChoice = Integer.parseInt(playerChoice.getText());
        String res = String.format("Results: \n"
                + "Player chose %s\n"
                + "Computer chose %s\n\n",choice(userChoice),choice(comChoice));
        switch (userChoice){
            case 1: 
                if (comChoice == 2 || comChoice == 5){
                    playerLoss(res);
                } else if (comChoice == 3 || comChoice == 4){
                    playerVictory(res);
                } else {
                    noWinner(res);
                }
                break;
            case 2: 
                if (comChoice == 3 || comChoice == 4){
                    playerLoss(res);
                } else if (comChoice == 1 || comChoice == 5){
                    playerVictory(res);
                } else {
                    noWinner(res);
                }
                break;
            case 3: 
                if (comChoice == 1 || comChoice == 5){
                    playerLoss(res);
                } else if (comChoice == 2 || comChoice == 4){
                    playerVictory(res);
                } else {
                    noWinner(res);
                }
                break;
            case 4: 
                if (comChoice == 1 || comChoice == 3){
                    playerLoss(res);
                } else if (comChoice == 2 || comChoice == 5){
                    playerVictory(res);
                } else {
                    noWinner(res);
                }
                break;
            case 5: 
                if (comChoice == 2 || comChoice == 4){
                    playerLoss(res);
                } else if (comChoice == 1 || comChoice == 3){
                    playerVictory(res);
                } else {
                    noWinner(res);
                }
                break;
            default:
                JOptionPane.showMessageDialog(this, "Please choose your Combatant!!");
                break;
        }
        reset();
    }//GEN-LAST:event_playActionPerformed
    // Actions done when the player losses
    public void playerLoss(String result){
        result = result + "YOU LOSE THIS ROUND";
        message.setText(result);
        JOptionPane.showMessageDialog(this, "Game Over! Computer has won!");
        int score = Integer.parseInt(cScore.getText());
        score++;
        cScore.setText(String.valueOf(score));
    }
    // Actions done when the player wins
    public void playerVictory(String result){
        result = result + "YOU WIN THIS ROUND";
        message.setText(result);
        JOptionPane.showMessageDialog(this, "Game Over! Player has won!");
        int score = Integer.parseInt(pScore.getText());
        score++;
        pScore.setText(String.valueOf(score));
    }
    // Actions done when it is a draw
    public void noWinner(String result){
        result = result + "NOBODY WINS THIS ROUND";
        message.setText(result);
        JOptionPane.showMessageDialog(this, "Draw!!!!");
    }
    // Resets the game
    public void reset(){
        rock.setSelected(false);
        paper.setSelected(false);
        scissors.setSelected(false);
        lizard.setSelected(false);
        spock.setSelected(false);
        message.setText(null);
    }
    // Returns the name of the choice (rock,scissors,paper,etc.)
    public String choice(int choice) {
        switch(choice){
            case 1:
                return "ROCK";
            case 2:
                return "PAPER";               
            case 3:
                return "SCISSORS";
            case 4:
                return "LIZARD";
            default:
                return "SPOCK";
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissorsLizardSpock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissorsLizardSpock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissorsLizardSpock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissorsLizardSpock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RockPaperScissorsLizardSpock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cScore;
    private javax.swing.ButtonGroup choice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JRadioButton lizard;
    private javax.swing.JTextArea message;
    private javax.swing.JTextField pScore;
    private javax.swing.JRadioButton paper;
    private javax.swing.JButton play;
    private javax.swing.JLabel playerChoice;
    private javax.swing.JButton quit;
    private javax.swing.JRadioButton rock;
    private javax.swing.JRadioButton scissors;
    private javax.swing.JRadioButton spock;
    // End of variables declaration//GEN-END:variables
}
