package rpgame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jeremy
 */

import rpgame.RPG;
import rpgame.Swordsman;
import rpgame.RPGCharacter;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;
public class GameMaster extends javax.swing.JFrame {

    /**
     * Creates new form GameMaster
     */
    public GameMaster() { 
        initComponents();
    }

    RPG rpg = new RPG();
    RPGCharacter hero;
    RPGCharacter monster;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        main = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cont = new javax.swing.JButton();
        start = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        journey = new javax.swing.JLabel();
        className = new javax.swing.JLabel();
        classImg = new javax.swing.JLabel();
        desc1 = new javax.swing.JLabel();
        desc2 = new javax.swing.JLabel();
        desc3 = new javax.swing.JLabel();
        swordClass = new javax.swing.JLabel();
        bowClass = new javax.swing.JLabel();
        magicClass = new javax.swing.JLabel();
        assassinClass = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        back = new javax.swing.JLabel();
        job = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        heroName = new javax.swing.JLabel();
        monsName = new javax.swing.JLabel();
        attack = new javax.swing.JLabel();
        skill = new javax.swing.JLabel();
        item = new javax.swing.JLabel();
        run = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        heroHP = new javax.swing.JProgressBar();
        heroMP = new javax.swing.JProgressBar();
        monsterHP = new javax.swing.JProgressBar();
        heroImg = new javax.swing.JLabel();
        roar = new javax.swing.JLabel();
        event = new javax.swing.JLabel();
        type = new javax.swing.JTextField();
        dieded = new javax.swing.JTextField();
        disabled = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        exitDed = new javax.swing.JLabel();
        dedHero = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jInternalFrame1.setMinimumSize(new java.awt.Dimension(670, 420));
        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(670, 420));

        main.setEnabled(false);
        main.setMinimumSize(new java.awt.Dimension(670, 420));
        main.setPreferredSize(new java.awt.Dimension(670, 420));
        main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainMouseClicked(evt);
            }
        });

        jPanel1.setLayout(null);

        cont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpgame/Untitled-10.png"))); // NOI18N
        cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contActionPerformed(evt);
            }
        });
        jPanel1.add(cont);
        cont.setBounds(380, 230, 200, 50);

        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpgame/Untitled-8.png"))); // NOI18N
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        jPanel1.add(start);
        start.setBounds(380, 160, 200, 60);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpgame/Untitled-9.png"))); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(360, 290, 230, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpgame/Untitled-1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 690, 420);

        main.addTab("", jPanel1);

        jPanel2.setLayout(null);

        journey.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        journey.setForeground(new java.awt.Color(204, 0, 0));
        journey.setText("START ADVENTURE");
        journey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                journeyMouseClicked(evt);
            }
        });
        jPanel2.add(journey);
        journey.setBounds(470, 360, 150, 19);

        className.setBackground(new java.awt.Color(255, 255, 255));
        className.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        className.setForeground(new java.awt.Color(153, 0, 0));
        className.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(className);
        className.setBounds(410, 60, 160, 40);

        classImg.setFont(new java.awt.Font("Tekton Pro", 1, 8)); // NOI18N
        jPanel2.add(classImg);
        classImg.setBounds(460, 90, 150, 280);

        desc1.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        desc1.setForeground(new java.awt.Color(153, 0, 0));
        jPanel2.add(desc1);
        desc1.setBounds(360, 210, 130, 20);

        desc2.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        desc2.setForeground(new java.awt.Color(153, 0, 0));
        jPanel2.add(desc2);
        desc2.setBounds(360, 110, 130, 20);

        desc3.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        desc3.setForeground(new java.awt.Color(153, 0, 0));
        jPanel2.add(desc3);
        desc3.setBounds(360, 160, 130, 20);

        swordClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpgame/Untitled--4png.png"))); // NOI18N
        swordClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                swordClassMouseClicked(evt);
            }
        });
        jPanel2.add(swordClass);
        swordClass.setBounds(100, 230, 60, 60);

        bowClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpgame/Untitled-3.png"))); // NOI18N
        bowClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bowClassMouseClicked(evt);
            }
        });
        jPanel2.add(bowClass);
        bowClass.setBounds(200, 230, 60, 60);

        magicClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpgame/Untitled-6.png"))); // NOI18N
        magicClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                magicClassMouseClicked(evt);
            }
        });
        jPanel2.add(magicClass);
        magicClass.setBounds(100, 320, 60, 70);

        assassinClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpgame/Untitled-2.png"))); // NOI18N
        assassinClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assassinClassMouseClicked(evt);
            }
        });
        jPanel2.add(assassinClass);
        assassinClass.setBounds(200, 320, 65, 60);

        name.setBackground(new java.awt.Color(213, 213, 213));
        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(name);
        name.setBounds(50, 90, 260, 40);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpgame/Untitled-7.png"))); // NOI18N
        jPanel2.add(back);
        back.setBounds(0, 0, 670, 420);
        jPanel2.add(job);
        job.setBounds(270, 360, 20, 20);

        main.addTab("", jPanel2);

        jPanel3.setLayout(null);

        heroName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        heroName.setForeground(new java.awt.Color(102, 255, 0));
        jPanel3.add(heroName);
        heroName.setBounds(20, 10, 630, 20);

        monsName.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        monsName.setForeground(new java.awt.Color(255, 0, 0));
        monsName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(monsName);
        monsName.setBounds(330, 40, 310, 20);

        attack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        attack.setForeground(new java.awt.Color(255, 255, 255));
        attack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attackMouseClicked(evt);
            }
        });
        jPanel3.add(attack);
        attack.setBounds(40, 340, 130, 30);

        skill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        skill.setForeground(new java.awt.Color(255, 255, 255));
        skill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                skillMouseClicked(evt);
            }
        });
        jPanel3.add(skill);
        skill.setBounds(40, 380, 130, 30);

        item.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        item.setForeground(new java.awt.Color(255, 255, 255));
        item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemMouseClicked(evt);
            }
        });
        jPanel3.add(item);
        item.setBounds(340, 340, 130, 30);

        run.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        run.setForeground(new java.awt.Color(255, 255, 255));
        run.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                runMouseClicked(evt);
            }
        });
        jPanel3.add(run);
        run.setBounds(340, 380, 130, 30);

        message.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        message.setForeground(new java.awt.Color(255, 255, 255));
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(message);
        message.setBounds(60, 360, 540, 30);

        heroHP.setBackground(new java.awt.Color(51, 51, 51));
        heroHP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        heroHP.setForeground(new java.awt.Color(255, 0, 0));
        heroHP.setMaximum(150);
        heroHP.setBorder(new javax.swing.border.MatteBorder(null));
        heroHP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        heroHP.setString("");
        heroHP.setStringPainted(true);
        jPanel3.add(heroHP);
        heroHP.setBounds(50, 50, 220, 20);

        heroMP.setBackground(new java.awt.Color(51, 51, 51));
        heroMP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        heroMP.setForeground(new java.awt.Color(0, 0, 255));
        heroMP.setMaximum(150);
        heroMP.setToolTipText("");
        heroMP.setBorder(new javax.swing.border.MatteBorder(null));
        heroMP.setString("");
        heroMP.setStringPainted(true);
        jPanel3.add(heroMP);
        heroMP.setBounds(50, 90, 220, 20);

        monsterHP.setBackground(new java.awt.Color(102, 102, 102));
        monsterHP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        monsterHP.setForeground(new java.awt.Color(204, 0, 0));
        monsterHP.setString("");
        monsterHP.setStringPainted(true);
        jPanel3.add(monsterHP);
        monsterHP.setBounds(390, 60, 190, 30);

        heroImg.setFont(new java.awt.Font("Tekton Pro", 1, 8)); // NOI18N
        jPanel3.add(heroImg);
        heroImg.setBounds(50, 60, 190, 280);
        jPanel3.add(roar);
        roar.setBounds(410, 90, 220, 290);

        event.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jPanel3.add(event);
        event.setBounds(0, 0, 660, 420);

        type.setEditable(false);
        type.setText("0");
        jPanel3.add(type);
        type.setBounds(600, 20, 20, 20);
        jPanel3.add(dieded);
        dieded.setBounds(600, 0, 20, 20);

        disabled.setEditable(false);
        disabled.setText("0");
        jPanel3.add(disabled);
        disabled.setBounds(600, 40, 20, 20);

        main.addTab("", jPanel3);

        jPanel4.setLayout(null);

        exitDed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpgame/dedExit.png"))); // NOI18N
        exitDed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitDedMouseClicked(evt);
            }
        });
        jPanel4.add(exitDed);
        exitDed.setBounds(520, 360, 140, 60);

        dedHero.setPreferredSize(new java.awt.Dimension(240, 140));
        jPanel4.add(dedHero);
        dedHero.setBounds(340, 100, 300, 210);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpgame/ded.png"))); // NOI18N
        jPanel4.add(jLabel2);
        jLabel2.setBounds(0, 0, 660, 420);

        main.addTab("", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        main.setSelectedIndex(1);
    }//GEN-LAST:event_startActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void contActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contActionPerformed
        JOptionPane.showMessageDialog(null,"Feature has not been added yet");
    }//GEN-LAST:event_contActionPerformed

    private void swordClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_swordClassMouseClicked
        job.setText("1");
        className.setText("Knight");
        classImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/swordIdle.png")));
        heroImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/swordAttk.gif")));
        dedHero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/swordDed.png")));
        desc1.setText("Strong Armor");
        desc2.setText("Medium Accuracy");
        desc3.setText("Bash Ability");
        
    }//GEN-LAST:event_swordClassMouseClicked

    private void bowClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bowClassMouseClicked
        job.setText("2");
        className.setText("Archer");
        classImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/bowIdle.png")));
        heroImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/bowAttk.gif")));
        dedHero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/bowDed.png")));
        desc1.setText("Moderate Armor");
        desc2.setText("Excellent Accuracy");
        desc3.setText("Burning Arrow Ability");
    }//GEN-LAST:event_bowClassMouseClicked

    private void magicClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_magicClassMouseClicked
        job.setText("3");
        className.setText("Mage");
        classImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/mageIdle.png")));
        heroImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/mageAttk.gif")));
        dedHero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/mageDed.png")));
        desc1.setText("Weak Armor");
        desc2.setText("Strong Attack");
        desc3.setText("Large Mana Pool");
    }//GEN-LAST:event_magicClassMouseClicked

    private void assassinClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assassinClassMouseClicked
        job.setText("4");
        className.setText("Assass5n");
        classImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/daggerIdle.png")));
        heroImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/daggerAttk.gif")));
        dedHero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/daggerDed.png")));
        desc1.setText("Weak Armor");
        desc2.setText("Double Damage Chance");
        desc3.setText("Invisibility Ability");
    }//GEN-LAST:event_assassinClassMouseClicked

    private void exitDedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitDedMouseClicked
        main.setSelectedIndex(0);
        name.setText(null);
        job.setText(null);
        className.setText(null);
        classImg.setIcon(null);
        heroImg.setIcon(null);
        dedHero.setIcon(null);
        event.setIcon(null);
        roar.setIcon(null);
        desc1.setText(null);
        desc2.setText(null);
        desc3.setText(null);
    }//GEN-LAST:event_exitDedMouseClicked

    private void journeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_journeyMouseClicked
        if (job.getText().equals("") || name.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Choose your Name / Class", "Error", 0);
        } else {
        if(rpg.confirm()){
            switch (Integer.parseInt(job.getText())){
                case 1:
                    hero = new Swordsman(name.getText(), 1);
                    break;
                case 2:
                    hero = new Archer(name.getText(), 1);
                    break;
                case 3:
                    hero = new Sorcerer(name.getText(), 1);
                    break;
                case 4:
                    hero = new Assassin(name.getText(), 1);
                    break;
                default:
            }
            setHeroHealth(hero.getHp());
            setHeroMana(hero.getMP());
            heroName.setText(getHeroName());
            main.setSelectedIndex(2);
                monster = new UnremarkableSlime(hero.getLevel());
                event.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/slimeHome.png")));
                roar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/slime.gif")));
                monsName.setText(getMonsName());
                setMonsterHealth(monster.getHp());
                rpg.playerEvent();
        }
        }
    }//GEN-LAST:event_journeyMouseClicked

    private void runMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_runMouseClicked
        if (type.getText().equals("0")){
            if (rpg.confirm()){
                JOptionPane.showMessageDialog(null,   "( ͡° ͜ʖ ͡°)( ͡° ͜ʖ ͡°)( ͡° ͜ʖ ͡°)( ͡° ͜ʖ ͡°)( ͡° ͜ʖ ͡°)\n"
                                                    + "|THE LABRYHTN WAS TRULY ENLDESS                        \n"
                                                    + "|<NO EXIT FOUND>                                       \n"
                                                    + "( ͡° ͜ʖ ͡°)( ͡° ͜ʖ ͡°)( ͡° ͜ʖ ͡°)( ͡° ͜ʖ ͡°)( ͡° ͜ʖ ͡°)");
                main.setSelectedIndex(3);}
        } else {
            rpg.playerEvent();
            type.setText("0");
        }
    }//GEN-LAST:event_runMouseClicked

    private void attackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attackMouseClicked
        boolean canBattle = true;
        if (type.getText().equals("1")){
            if (hero.getMP() >= 60){
                int remMp = hero.takeMP(70);            
                heroMP.setValue(remMp);
                String skill = name.getText() + " used " +attack.getText();
                JOptionPane.showMessageDialog(null, skill, "SKILL USED", 1);
            } else { 
                JOptionPane.showMessageDialog(null, "NOT ENOUGH MANA", "SKILL CANNOT BE USED", 0);
                canBattle = false;
            }
        }
        if (canBattle){
            dieded.setText("0");            
            rpg.normal(hero, monster);
            results();
        }
    }//GEN-LAST:event_attackMouseClicked

    private void skillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_skillMouseClicked
        if (type.getText().equals("0")){
            type.setText("1");
            Hero hero1 = (Hero) hero;
            rpg.skillTree(hero1);
        } else {
            if (hero.getMP() >= 100){
                String skilL = name.getText() + " casted " +skill.getText();
                JOptionPane.showMessageDialog(null, skilL, "SKILL USED", 1);
                disabled.setText("2");
                int remMp = hero.takeMP(100);            
                heroMP.setValue(remMp);
                rpg.playerEvent();
            } else { 
                JOptionPane.showMessageDialog(null, "NOT ENOUGH MANA", "SKILL CANNOT BE USED", 0);  
            }
            type.setText("0");
        }
        
    }//GEN-LAST:event_skillMouseClicked

    private void itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemMouseClicked
        if (type.getText().equals("0")){
            JOptionPane.showMessageDialog(null, "Feature Unavailable", "!Sorry!", 0);
        }
    }//GEN-LAST:event_itemMouseClicked

    private void mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mainMouseClicked
    // Random Monster Generator
    public void generateMonster(){
        int rand = rpg.randInt(1, 5);
        switch (rand){
                case 1:
                    monster = new PoisonEnt(hero.getLevel());
                    event.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/entHome.png")));
                    roar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/ent.gif")));
                    break;
                case 2:
                    monster = new DarkMagician(hero.getLevel());
                    event.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/mageHome.png")));
                    roar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/dark.gif")));
                    break;
                case 3:
                    monster = new FireElemental(hero.getLevel());
                    event.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/elementalHome.png")));
                    roar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/ifrit.gif")));
                    break;
                case 4:
                    monster = new Raijin(hero.getLevel());
                    event.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/orcHome.png")));
                    roar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/spark.gif")));
                    break;
                default:
                    monster = new UnremarkableSlime(hero.getLevel());
                    event.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/slimeHome.png")));
                    roar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/slime.gif")));
        }
        monsName.setText(getMonsName());
        monster.updateHealth();
        setMonsterHealth(monster.getHp());
        rpg.playerEvent();
    }
    // Generates a boss
    public void generateBoss(){
        monster = new ObeliskTheTormentor(hero.getLevel());
        event.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/bossHome.png")));
        roar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RPG/torment.gif")));
        monsName.setText(getMonsName());
        setMonsterHealth(monster.getHp());
        rpg.playerEvent();
    }
    //checks the result of the battle
    public void results(){
        if (Integer.parseInt(dieded.getText()) == 1){
                JOptionPane.showMessageDialog(null, "VICTORY!!!", "!GL FURTHER!", 2);
                hero.levelUp(1);
                JOptionPane.showMessageDialog(null, "YOU ARE NOW LEVEL " +hero.getLevel(), "LEVEL UP!", 2);
                heroName.setText(getHeroName());
                hero.updateHealth();
                hero.updateMana();
                setHeroHealth(hero.getHp());
                setHeroMana(hero.getMP());
                disabled.setText("0");
                if (hero.getLevel() % 10 != 0){
                    generateMonster();
                } else {
                    JOptionPane.showMessageDialog(null, "BOSS BATTLE", "!!!WARNING!!!", 0);
                    generateBoss();
                }
            } else if (Integer.parseInt(dieded.getText()) == -1){
                JOptionPane.showMessageDialog(null, "Defeated!!", "!GL NEXT TIME!", 2);
                main.setSelectedIndex(3);
            }
    }
    //Sets hero's Max HP
    public void setHeroHealth(int hP){
        heroHP.setMaximum(hP);
        heroHP.setValue(hP);
    }
    //Sets hero's Max HP
    public void setHeroMana(int mP){
        heroMP.setMaximum(mP);
        heroMP.setValue(mP);
    }
    //Sets monster's Max HP
    public void setMonsterHealth(int hP){
        monsterHP.setMaximum(hP);
        monsterHP.setValue(hP);
    }
    // Gets the hero name and level
    public String getHeroName(){
        String namE = String.format("Lvl: %d %s", hero.getLevel(), hero.getName());
        return namE;
    }
    // Gets the monster name and level
    public String getMonsName(){
        String namE = String.format("Lvl: %d %s", monster.getLevel(), monster.getName());
        return namE;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameMaster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assassinClass;
    public static javax.swing.JLabel attack;
    private javax.swing.JLabel back;
    private javax.swing.JLabel bowClass;
    private javax.swing.JLabel classImg;
    private javax.swing.JLabel className;
    private javax.swing.JButton cont;
    private javax.swing.JLabel dedHero;
    private javax.swing.JLabel desc1;
    private javax.swing.JLabel desc2;
    private javax.swing.JLabel desc3;
    public static javax.swing.JTextField dieded;
    public static javax.swing.JTextField disabled;
    private javax.swing.JLabel event;
    private javax.swing.JButton exit;
    private javax.swing.JLabel exitDed;
    public static javax.swing.JProgressBar heroHP;
    private javax.swing.JLabel heroImg;
    public static javax.swing.JProgressBar heroMP;
    private javax.swing.JLabel heroName;
    public static javax.swing.JLabel item;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField job;
    private javax.swing.JLabel journey;
    private javax.swing.JLabel magicClass;
    private javax.swing.JTabbedPane main;
    public static javax.swing.JLabel message;
    private javax.swing.JLabel monsName;
    public static javax.swing.JProgressBar monsterHP;
    private static javax.swing.JTextField name;
    private javax.swing.JLabel roar;
    public static javax.swing.JLabel run;
    public static javax.swing.JLabel skill;
    private javax.swing.JButton start;
    private javax.swing.JLabel swordClass;
    public static javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
